---
- name: kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: make kernel modules persistent
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf

- name: sysctl settings
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

- name: prerequisites and sundries
  ansible.builtin.apt:
    name: 
      - apt-transport-https
      - python3-pip
      - open-iscsi
      - nfs-common
      - etcd-client
      - protobuf-compiler
      - conntrack
      - socat
    update_cache: yes

- name: python prerequisites
  ansible.builtin.pip:
    name: kubernetes>=24.2.0
    break_system_packages: true

- name: gpg key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_minor_version }}/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes.asc
    mode: '0644'

- name: repository
  ansible.builtin.deb822_repository:
    name: kubernetes
    uris: https://pkgs.k8s.io/core:/stable:/v{{ k8s_minor_version }}/deb/
    suites: /
    signed_by: /etc/apt/keyrings/kubernetes.asc
    install_python_debian: true

- name: install
  ansible.builtin.apt:
    name:
      - kubelet={{ k8s_version }}-*
      - kubeadm={{ k8s_version }}-*
      - kubectl={{ k8s_version }}-*
    update_cache: yes

- name: hold kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: bash completion
  ansible.builtin.shell: 
    cmd: kubectl completion bash > /etc/bash_completion.d/kubectl
    creates: "/etc/bash_completion.d/kubectl"

- name: kubeadm init
  ansible.builtin.command:
    cmd: /usr/bin/kubeadm init --config /etc/kubernetes/kubeadm-init.yaml --upload-certs 
    creates: /etc/kubernetes/pki/ca.crt
  when: k8s_initial_master in ansible_facts['all_ipv4_addresses']

- name: kubeadm join
  ansible.builtin.command:
    cmd: /usr/bin/kubeadm join --config /etc/kubernetes/kubeadm-join.yaml
    creates: /etc/kubernetes/pki/ca.crt
  throttle: 1
  when: k8s_initial_master not in ansible_facts['all_ipv4_addresses']

- name: collect kubelet serving csrs
  ansible.builtin.shell: |
    for i in $(seq 1 30); do
      csrs=$(kubectl get csr --field-selector='spec.signerName=kubernetes.io/kubelet-serving' -o jsonpath='{.items[*].metadata.name}')
      [ $(echo $csrs | wc -w) -ge {{ k8s_cluster_ips | length }} ] && break
      sleep 2
    done
    echo $csrs
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: k8s_kubelet_csrs
  when: 
    - k8s_initial_master in ansible_facts['all_ipv4_addresses']
  changed_when: false
  failed_when: false

- name: sign kubelet serving csrs
  ansible.builtin.shell: kubectl certificate approve {{ k8s_kubelet_csrs.stdout }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: 
    - k8s_initial_master in ansible_facts['all_ipv4_addresses']
    - k8s_kubelet_csrs.stdout | length > 0
  changed_when: false

- name: download calico operator
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/{{ item }}
    dest: /etc/kubernetes/components/{{ item }}
    mode: '0644'
  when: 
    - k8s_initial_master in ansible_facts['all_ipv4_addresses']
    - k8s_network == 'calico'
  loop:
    - operator-crds.yaml
    - tigera-operator.yaml

- name: install calico
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    src: /etc/kubernetes/components/{{ item }}
  when: 
    - k8s_initial_master in ansible_facts['all_ipv4_addresses']
    - k8s_network == 'calico'
  retries: 10
  delay: 10
  register: result
  until: result is successful
  loop:
    - operator-crds.yaml
    - tigera-operator.yaml
    - custom-resources.yaml

- name: install flannel
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    src: /etc/kubernetes/components/flannel.yaml
  when: 
    - k8s_initial_master in ansible_facts['all_ipv4_addresses']
    - k8s_network == 'flannel'

- name: install weave
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    src: /etc/kubernetes/components/weave.yaml
  when: 
    - k8s_initial_master in ansible_facts['all_ipv4_addresses']
    - k8s_network == 'weave'

- name: iscsi_tcp module for longhorn
  community.general.modprobe:
    name: iscsi_tcp
    state: present

- name: make iscsi_tcp module persistent
  ansible.builtin.copy:
    content: 'iscsi_tcp'
    dest: /etc/modules-load.d/longhorn.conf

- name: check for multipathd
  ansible.builtin.stat:
    path: /usr/sbin/multipathd
  register: k8s_multipathd

- name: keep multipathd away from longhorn volumes
  ansible.builtin.blockinfile:
    path: /etc/multipath.conf
    create: yes
    mode: '0644'
    block: |
      blacklist {
          devnode "^sd[a-z0-9]+"
      }
  register: k8s_multipath_conf
  when: k8s_multipathd.stat.exists

- name: restart multipathd
  ansible.builtin.systemd:
    name: multipathd
    state: restarted
  when: k8s_multipath_conf is changed

- name: iscsid service for longhorn
  ansible.builtin.systemd:
    name: iscsid
    state: started
    enabled: yes

- name: download longhorn config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/longhorn/longhorn/v{{ k8s_longhorn_version }}/deploy/longhorn.yaml
    dest: /etc/kubernetes/components/longhorn.yaml
    mode: '0644'
  when: k8s_initial_master in ansible_facts['all_ipv4_addresses']

- name: install longhorn
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    src: /etc/kubernetes/components/longhorn.yaml
  when: k8s_initial_master in ansible_facts['all_ipv4_addresses']

- name: download metrics server
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/metrics-server/releases/download/v{{ metrics_server_version }}/components.yaml
    dest: /etc/kubernetes/components/metrics-server.yaml
    mode: '0644'
  when: k8s_initial_master in ansible_facts['all_ipv4_addresses']

- name: install metrics server
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    src: /etc/kubernetes/components/metrics-server.yaml
  when: 
    - k8s_initial_master in ansible_facts['all_ipv4_addresses']
    - not k8s_prometheus

- name: download ingress controller
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v{{ ingress_version }}/deploy/static/provider/cloud/deploy.yaml
    dest: /etc/kubernetes/components/ingress-controller.yaml
    mode: '0644'
  when: k8s_initial_master in ansible_facts['all_ipv4_addresses']

- name: install ingress controller
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    src: /etc/kubernetes/components/ingress-controller.yaml
  when: k8s_initial_master in ansible_facts['all_ipv4_addresses']
  failed_when: false

- name: patch ingress controller
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    src: /etc/kubernetes/components/ingress-patch.yaml
  when: k8s_initial_master in ansible_facts['all_ipv4_addresses']
  failed_when: false

- name: postgresql operator namespace
  kubernetes.core.k8s:
    name: "{{ k8s_postgresql_operator_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
  when: 
    - k8s_initial_master in ansible_facts['all_ipv4_addresses']
    - k8s_postgresql_operator != "none"

- name: setup postgresql operator
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    src: /etc/kubernetes/components/{{ item }}
  when: 
    - k8s_initial_master in ansible_facts['all_ipv4_addresses']
    - k8s_postgresql_operator != "none"
  retries: 10
  register: result
  until: result is successful
  loop:
    - operatorconfiguration.crd.yaml
    - postgresql-operator-default-configuration.yaml
    - operator-service-account-rbac.yaml

- name: install postgresql operator
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/kubernetes/admin.conf
    src: /etc/kubernetes/components/postgres-operator.yaml
  when: 
    - k8s_initial_master in ansible_facts['all_ipv4_addresses']
    - k8s_postgresql_operator == "install"
