---
crio_version: v1.34
crio_repo: https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ crio_version }}/deb
crio_skopeo: false
crio_cni: false
cni_plugin_version: v1.9.1
cni_plugin_arch: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' }}"
cni_plugin_url: https://github.com/containernetworking/plugins/releases/download/{{ cni_plugin_version }}/cni-plugins-linux-{{ cni_plugin_arch }}-{{ cni_plugin_version }}.tgz
