---
- name: prerequisites
  apt:
    name: apt-transport-https
    update_cache: yes

- name: gpg key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: repository
  ansible.builtin.deb822_repository:
    name: docker
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    signed_by: /etc/apt/keyrings/docker.asc
    install_python_debian: true

- name: install
  apt:
    name: docker-ce
    update_cache: yes
