---
k8s_install: true

k8s_pod_cidr: 172.31.0.0/16
k8s_allow_scheduling_masters: false
k8s_kube_vip: false
k8s_network: calico
k8s_prometheus: false
k8s_postgresql_operator: none
k8s_postgresql_operator_namespace: default

k8s_version: 1.34.12
k8s_minor_version: "{{ k8s_version.split('.')[0:2] | join('.') }}"
calico_version: 3.31.7
k8s_longhorn_version: 1.12.1
metrics_server_version: 0.8.1
ingress_version: 1.15.1
k8s_prometheus_version: "0.18"
k8s_kube_vip_version: v1.2.4
